import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto('http://localhost:8096/er.html');
await p.waitForSelector('#svg-wrap svg', { timeout: 20000 });
await p.waitForTimeout(400);
await p.click('#mode-nested');
await p.waitForSelector('#svg-wrap rect.nest-tbl', { timeout: 10000 });
await p.waitForTimeout(300);
await (await p.$('rect.nest-tbl[data-tbl="mm_block_list"]')).dblclick();
await p.waitForTimeout(500);
const lines = await p.$$eval('#svg-wrap svg path', els => els.map(e => e.getAttribute('d')).filter(d => d && d.startsWith('M')));
const rects = await p.$$eval('rect.nest-tbl', els => els.map(e => ({ n: e.getAttribute('data-tbl'), x: e.getAttribute('x'), y: e.getAttribute('y'), w: e.getAttribute('width'), h: e.getAttribute('height') })));
console.log('rects:', JSON.stringify(rects));
console.log('lines:', lines.join('\n'));
await b.close();
