import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto('http://localhost:8096/er.html');
await p.waitForSelector('#svg-wrap svg', { timeout: 20000 });
await p.waitForTimeout(400);
await (await p.$('rect.tbl[data-tbl="mm_block_list"]')).dblclick();
await p.waitForTimeout(500);
const names = await p.$$eval('rect.tbl', els => els.map(e => e.getAttribute('data-tbl')));
console.log('visible tables:', JSON.stringify(names));
console.log('info:', await p.textContent('#info'));
await b.close();
